#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
    type="prompt"
    alignment = 'left'
    newline=true

    [[blocks.segments]]
        foreground="p:os"
        style="plain"
        template="{{ .Icon }} "
        type="os"

    [[blocks.segments]]
        foreground="p:blue"
        style="plain"
        template="{{.UserName}}@{{.HostName}} "
        type="session"

    [[blocks.segments]]
        type="path"
        style="plain"
        foreground="green"
        template="<b>{{ .Path }} </b>"

        [blocks.segments.properties]
            style='folder'


    [[blocks.segments]]
        type = "git"
        style = "plain"
        foreground = "magenta"
        template = "<b>{{ .HEAD }} {{if or (gt .StashCount 0) (.Working.Changed) (.Staging.Changed)}}<red>[{{if gt .StashCount 0}}\\${{end}}{{if gt .Working.Deleted 0}}✘{{end}}{{if or (gt .Working.Added 0) (gt .Working.Modified 0)}}!{{end}}{{if .Staging.Changed}}+{{end}}{{if gt .Working.Untracked 0}}?{{end}}{{if gt .Ahead 0}}⇡{{end}}]</>{{end}}</b>"

        [blocks.segments.properties]
            fetch_status = true
            fetch_upstream_icon = true

    [[blocks.segments]]
        foreground="green"
        style="plain"
        template="<white> via </> {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}"
        type="node"
        [blocks.segments.properties]
            fetch_package_manager=false

    [[blocks.segments]]
        foreground="yellow"
        style="plain"
        template="<white> via </> {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}"
        type="python"

    [[blocks.segments]]
        foreground="blue"
        style="plain"
        template="<white> via </> {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
        type="go"


    [[blocks.segments]]
        template="<white> via </> {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
        style="plain"
        type="lua"

[[blocks]]
    type="prompt"
    alignment="left"
    newline=true

    [[blocks.segments]]
        type="text"
        style="plain"
        foreground_templates = [
            "{{if gt .Code 0}}red{{end}}",
            "{{if eq .Code 0}}magenta{{end}}"
        ]
        template="\u276f"
        foreground="blue"


[palette]
    os="#ACB0BE"
    closer="p:os"
    pink="#F5BDE6"
    lavender="#B7BDF8"
    blue= "#8AADF4"

[transient_prompt]
    background="transparent"
    foreground_templates = [
        "{{if gt .Code 0}}red{{end}}",
        "{{if eq .Code 0}}magenta{{end}}"
    ]
    template="❯ "
