import = [
    "~/.config/alacritty/catppuccin-mocha.toml",
]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 20, lines = 100 }
padding = {x = 10, y = 5}
decorations = "None"
opacity = 0.8
blur = true
startup_mode = "Maximized"

[font]
normal = { family="GoMonoNerdFont", style = "Regular" }
bold = { family="GoMonoNerdFont", style = "Bold" }
italic = {family="CaskaydiaCoveNerdFont", style = "Medium Italic"}
bold_italic = {family="VictorMonoNF", style = "Bold Italic"}
size = 18

[shell]
program = "/bin/zsh"
